name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my-docker-app .

    - name: Save Docker image as tar
      run: docker save my-docker-app -o my-docker-app.tar

    - name: Copy image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "my-docker-app.tar"
        target: "~/"

    - name: Load & Run Docker container on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load -i ~/my-docker-app.tar
          docker stop my-docker-app || true
          docker rm my-docker-app || true
          docker run -d -p 80:5000 --name my-docker-app my-docker-app

